authapp/urls.py
from django.conf.urls import url

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    url(r'^login/$', authapp.login, name='login'),
    url(r'^logout/$', authapp.logout, name='logout'),
    url(r'^register/$', authapp.register, name='register'),
    url(r'^edit/$', authapp.edit, name='edit'),
    
]

    

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
    path('ajaxdelete/<int:pk>/', basketapp.basket_ajaxdelete, name='delete'),
    
]

    

yoyaml_lesson1/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
# import authapp.views as authapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.index, name='index'),
    path('products/<int:pk>/', mainapp.products, name='products'),
    path('contacts/', mainapp.contacts, name="contacts"),
    path('product_detail/<int:pk>/', mainapp.product_detail, name='product_detail'),
    path('auth/', include ('authapp.urls', namespace='auth')),
    path('basket', include ('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basketapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Product


class Basket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="baskets")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)
    add_datetime = models.DateTimeField(verbose_name='время добавления', auto_now_add=True)

    def _get_product_cost(self):
        "return cost of all products this type"
        return self.product.price * self.quantity

    product_cost = property(_get_product_cost)

    def _get_total_quantity(self):
        "return total quantity for user"
        _items = Basket.objects.filter(user=self.user)
        _totalquantity = sum(list(map(lambda x: x.quantity, _items)))
        return _totalquantity

    total_quantity = property(_get_total_quantity)

    def _get_total_cost(self):
        "return total cost for user"
        _items = Basket.objects.filter(user=self.user)
        _totalcost = sum(list(map(lambda x: x.product_cost, _items)))
        return _totalcost

    total_cost = property(_get_total_cost)

basketapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from basketapp.models import Basket
from mainapp.models import Product
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from django.template.loader import render_to_string
from django.http import JsonResponse, Http404

@login_required
def basket(request):
    title = 'корзина'

    basket_items = Basket.objects.filter(user=request.user).order_by('product__category')

    content = {
        'title': title,
        'basket_items': basket_items,
    }

    return render(request, 'basketapp/basket.html', content)

@login_required
def basket_add(request, pk):
    product = get_object_or_404(Product, pk=pk)
    old_basket_item = Basket.objects.filter(user=request.user, product=product)
    
    if old_basket_item:
        old_basket_item[0].quantity += 1
        old_basket_item[0].save()
    else:
        new_basket_item = Basket(user=request.user, product=product)
        new_basket_item.quantity += 1
        new_basket_item.save()
    
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)
    basket_record.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_edit(request, pk, quantity):
    if request.is_ajax():
        quantity = int(quantity)
        new_basket_item = Basket.objects.get(pk=int(pk))

        if quantity > 0:
            new_basket_item.quantity = quantity
            new_basket_item.save()
        else:
            new_basket_item.delete()

        basket_items = Basket.objects.filter(user=request.user).order_by('product__category')

        content = {
            'basket_items': basket_items,
        }

        # result = render_to_string('basketapp/includes/inc_basket_list.html', content)
        result = render_to_string('basketapp/basket.html', content)

        return JsonResponse({'result': result})
    else:
        return Http404


def basket_ajaxdelete(request, pk):
    if request.is_ajax():
        new_basket_item = Basket.objects.get(pk=int(pk))
        new_basket_item.delete()

        basket_items = Basket.objects.filter(user=request.user).order_by('product__category')

        content = {
            'basket_items': basket_items,
        }

        result = render_to_string('basketapp/basket.html', content)

        return JsonResponse({'result': result})
    else:
        return Http404

basketapp/templates/basketapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/basket_scripts.js' %}"></script>
    {% endblock %}
</head>
<body>
	<div class="basket_container">        
        <div class="h2 text-center head">
            Ваша корзина, {% if user.first_name %}{{ user.first_name|title}}{% else %}Пользователь{% endif %}
        </div>
        
        
        {% block content %}

        {% endblock %}
        
	</div>
</body>
</html>

basketapp/templates/basketapp/basket.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Ваша корзина</title>
    {% block css %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link rel="stylesheet" href={% static 'css/basket.css' %}>
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/basket_scripts.js' %}"></script>
    {% endblock %}
</head>
<body>
    <div class="container">
    <div class="basket_container">
        <div class="basket_title">
            <p>Ваша корзина, {% if user.first_name %}{{ user.first_name|title}}{% else %}Пользователь{% endif %}</p>
        </div>
        <div class="basket_list">
            {% for item in basket_items %}
            <div class="basket_record">
                <div class="basket_product_image">
                    <img src="{{ item.product.image.url }}" alt="{{ item.product.short_desc }}">
                </div>
                <div class="basket_product_category">
                    <p>{{ item.product.category.name }}</p>
                </div>
                <div class="basket_product_name">
                    <p>{{ item.product.name }}</p>
                </div>
                <div class="basket_product_quantity">
                    <input type="number" name="{{ item.pk }}" min="0" value="{{ item.quantity }}">
                </div>
                <div class="basket_product_price">
                    <p>{{ item.product.price }}&nbspруб.</p>
                </div>
                <div class="basket_product_remove_button">
                    <button class="btn btn-outline-danger" onclick="location.href='{% url 'basket:remove' item.pk %}'">УДАЛИТЬ</button>
                </div>
            {% endfor %}
            </div>
        </div>
        <hr>
        <div class="basket_footer">
            <div class="basket_summary">
               <p>В корзине {{ basket_items.0.total_quantity }} товаров. Общей стоимостью {{ basket_items.0.total_cost }} руб.</p>
            </div>
            <div class="basket_checkout">
                <button class="btn btn-primary btn-lg">ОФОРМИТЬ ЗАКАЗ</button>
            </div>
        </div>
        <div class="return_to_main_button">
            <button class="btn btn-secondary" onclick="location.href='{% url 'index' %}'">На главную</button>
        </div>
    </div>
</body>
</html>