authapp/urls.py
from django.conf.urls import url

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    url(r'^login/$', authapp.login, name='login'),
    url(r'^logout/$', authapp.logout, name='logout'),
    url(r'^register/$', authapp.register, name='register'),
    url(r'^edit/$', authapp.edit, name='edit'),
    
]

    

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
    path('ajaxdelete/<int:pk>/', basketapp.basket_ajaxdelete, name='delete'),
    
]

    

yoyaml_lesson1/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
# import authapp.views as authapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.index, name='index'),
    path('products/<int:pk>/', mainapp.products, name='products'),
    path('contacts/', mainapp.contacts, name="contacts"),
    path('product_detail/<int:pk>/', mainapp.product_detail, name='product_detail'),
    path('auth/', include ('authapp.urls', namespace='auth')),
    path('basket', include ('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href={% static '/css/style2.css' %}>
</head>
<body>
    <header>
        <div class="header">
            <a href="index.html"><img class="logo" src={% static '/img/logo.jpg' %} alt="logo"></a>
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href={% url 'index' %}>Главная</a></li>
                <li class="nav-item">
                    <a class="nav-link" href={% url 'products' pk=0 %}>Каталог</a></li>
                <li class="nav-item">
                    <a class="nav-link" href={% url 'contacts' %}>Контакты</a></li>
                </li>
                    {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth:edit' %}">
                        {{ user.first_name|default:'Пользователь' }}
                    </a>
                </li>
                    {% endif %}
                <li class="nav-item">
                        {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'auth:logout' %}">выйти</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'auth:login' %}">войти</a>
                    {% endif %}
                </li>
                <li>
                    <a href="#" class="search"></a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'basket:view' %}" class="nav-link"><img src={% static '/img/basket.png' %}
                    <span>
                        {% if basket %}
                            {{ basket.0.total_cost|floatformat:0 }} руб ({{ basket.0.total_quantity }} шт)
                        {% endif %}
                    </span>
                    </a>
                </li>
            </ul>
        </div>
    </header>
    <div class="container">
        <div class="content">
        {% block content %}
        {% endblock %}
        </div>
    </div>
    <footer>
        <hr/>
        <div class="footer">
            <p>&copy Eventus Group 2018</p>
            <p>Все права защищены</p>
        </div>
    </footer>
</body>
</html>

templates/catalog.html
{% extends "base.html" %}

{% block title %}
Каталог товаров
{% endblock %}

{% load static %}
{% block content %}
    <hr />
	</header>
	<h3 class="goods">Каталог товаров</h3>
        <ul class="nav justify-content-center">
            {% for link in links_menu %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'products' pk=link.id %}">{{ link.name }}</a>
            </li>
            {% endfor %}
        </ul>
            {% for product in products%}
                <div>
                    <p><img class="catalog" src="/media/{{ product.image }}" alt="{{ product.name }}"></p>
                    <a href={% url 'product_detail' product.id %}>{{ product.name }}</a>
                    <p>{{ product.short_decription }}</p>
                    <p>Цена: {{ product.price }} руб.</p>
                    <a href="{% url 'basket:add' product.pk %}"> <button type="button" class ="btn btn-primary">Добавить в корзину</button></a>
                </div>
            {% endfor %}
{% endblock %}

templates/contacts.html
{% extends "base.html" %}

{% block title %}
Наши контакты
{% endblock %}

{% block content %}
    <hr />
	<h3 class="goods" >Наши контакты</h3>
        <p>ООО " Эвентус Групп"
        <br>
    <h2 class="goods">Адрес</h2>
        443041, г. Самара
        <br>
        ул. Ленинская, 147
        <br>
        8 960 827 50 00
        <br>
        <a href="mailto:shop@yoya.ml">shop@yoya.ml</a>
        </p>
        <h3 class="goods">Напишите нам</h3>
        <div>
        <form class="form-horizontal" method="post">
        {% csrf_token %}
            {{  form.as_p }}
            <input class="form-control-feedback" type="submit" value="ОТПРАВИТЬ СООБЩЕНИЕ">
        </form>
        </div>
        <div>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2390.3119518344406!2d50.110138351370956!3d53.19432137984897!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x41661e6bd1142023%3A0x895acbd0f20d8d98!2z0YPQuy4g0JvQtdC90LjQvdGB0LrQsNGPLCAxNDcsINCh0LDQvNCw0YDQsCwg0KHQsNC80LDRgNGB0LrQsNGPINC-0LHQuy4sIDQ0MzA0MQ!5e0!3m2!1sru!2sru!4v1532493762716" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}
    Главная страница
{% endblock %}

{% load static %}

{% block content %}
        </div class="content">
        <h1>Интернет-магазин детских колясок</h1>
        <hr/>

    <h3 class="goods">
        <p> Добро пожаловать в наш интернет магазин</p>
        <p>"Счастливая Мама"</p>
        <p>Здесь вы найдете коляски на любой вкус и кошелек</p>
    </h3>
    <img src={% static 'img/main.jpg' %} alt="main logo">
        {% endblock %}

templates/product_detail.html
{% extends "base.html" %}

{% block title %}

{% endblock %}

{% load static %}


{% block content %}
    <p><img class="catalog" src="/media/{{ product.image }}" alt="{{ product.name }}"></p>
    <p>{{ product.name }}</p>
    <p>{{ product.category }}</p>
    <p>{{ product.description }}</p>
    <p> Цена: {{ product.price }} руб.</p>


    <a href="{% url 'basket:add' product.pk %}"> <button type="button" class ="btn btn-primary">Добавить в корзину</button></a>
    <p></p><a href={% url 'products' pk=0 %}>Вернуться в каталог</a></p>

{% endblock %}